import Providers from "@/lib/Providers";
import "./globals.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Metro G",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Providers>
  );
}
